dig-now: resolve more gcc warnings.
turns out I'm not allowed to have unused functions.
so much for forward planning.

also, apparently 0 is signed!  who would have known?

In file included from /home/runner/work/dfhack/dfhack/library/include/Error.h:31,
                 from /home/runner/work/dfhack/dfhack/library/include/BitArray.h:26,
                 from /home/runner/work/dfhack/dfhack/library/include/DataDefs.h:37,
                 from /home/runner/work/dfhack/dfhack/library/include/DataIdentity.h:38,
                 from /home/runner/work/dfhack/dfhack/library/include/DataFuncs.h:30,
                 from /home/runner/work/dfhack/dfhack/plugins/dig-now.cpp:5:
/home/runner/work/dfhack/dfhack/library/include/MiscUtils.h: In instantiation of ‘T clip_range(T, T1, T2) [with T = long unsigned int; T1 = int; T2 = long unsigned int]’:
/home/runner/work/dfhack/dfhack/plugins/dig-now.cpp:108:23:   required from here
/home/runner/work/dfhack/dfhack/library/include/MiscUtils.h:553:11: error: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Werror=sign-compare]
  553 |     if (a < minv) return minv;
      |         ~~^~~~~~